### 10/8 資料處理工具  
##### 郭又瑄


![](dev-1.png)

#### 常見套件

In [1]:
import numpy as np
import pandas as pd
import sklearn 

#### 資料結構 - list

In [2]:
myList = []

In [3]:
myData = ['S',96,54,33,85,77]

In [4]:
myData

['S', 96, 54, 33, 85, 77]

#### 資料結構 - tuple

In [5]:
myTuple = ()

In [6]:
myData = ('S',96,54,33,85,77)
myData

('S', 96, 54, 33, 85, 77)

In [7]:
myData[1] 

96

In [8]:
myData[1] = 6

TypeError: 'tuple' object does not support item assignment

#### 資料結構 - dictionary

In [9]:
Name = 'Nikki'
Date = '8/13'
Single = True

In [10]:
Me = {
    'Name' : Name,
    'Date' : Date,
    'Single' : Single
}

In [11]:
Me

{'Date': '8/13', 'Name': 'Nikki', 'Single': True}

In [12]:
len(Me)

3

In [13]:
Me['Name']

'Nikki'

In [14]:
Me['Gender'] = 'G'

In [15]:
Me

{'Date': '8/13', 'Gender': 'G', 'Name': 'Nikki', 'Single': True}

In [16]:
del Me['Date']

In [17]:
Me

{'Gender': 'G', 'Name': 'Nikki', 'Single': True}

In [18]:
'Name' in Me

True

In [19]:
'Nikki' in Me

False

In [20]:
for item in Me:
    print(item)

Name
Single
Gender


In [21]:
[item for item in Me]

['Name', 'Single', 'Gender']

In [22]:
Me

{'Gender': 'G', 'Name': 'Nikki', 'Single': True}

In [23]:
Me.keys()

dict_keys(['Name', 'Single', 'Gender'])

In [24]:
Me.values()

dict_values(['Nikki', True, 'G'])

In [25]:
for key, value in Me.items():
    print(value)

Nikki
True
G


In [26]:
[value for key, value in Me.items()]

['Nikki', True, 'G']

#### 套件 - Numpy

In [27]:
array1 = np.array([6,9,4])
array2 = np.array([8,2,9])

In [28]:
array1 + array2

array([14, 11, 13])

In [29]:
print(array1.ndim, array1.shape, array1.dtype)

1 (3,) int32


In [30]:
array4 = np.array([1, 2, 3, 4, 5, 6])
array4 = array4.reshape(3,2)

In [31]:
array4.shape

(3, 2)

In [32]:
array1

array([6, 9, 4])

In [33]:
array2

array([8, 2, 9])

In [34]:
np.append(array1,array2,axis=0)    #向量

array([6, 9, 4, 8, 2, 9])

In [35]:
np.append(array1,array2)    #向量

array([6, 9, 4, 8, 2, 9])

In [36]:
np.append(array1,array2,axis=1) 

AxisError: axis 1 is out of bounds for array of dimension 1

In [37]:
array1.shape    #向量

(3,)

In [38]:
array1 = np.reshape(array1,(3,1))

In [39]:
array1.shape    #矩陣

(3, 1)

In [40]:
array2 = np.reshape(array2,(3,1))

In [41]:
np.append(array1,array2,axis=1)      #矩陣

array([[6, 8],
       [9, 2],
       [4, 9]])

In [42]:
np.append(array1,array2,axis=0) 

array([[6],
       [9],
       [4],
       [8],
       [2],
       [9]])

In [43]:
array4 = array4.astype('int16')
array4.dtype

dtype('int16')

In [44]:
mylist = [2,6,5,8,7]
np.asarray(mylist)

array([2, 6, 5, 8, 7])

In [45]:
mylist = (2,6,5,8,7)
np.array(mylist)

array([2, 6, 5, 8, 7])

#### 套件 - pandas

In [46]:
data = pd.read_table("glass.txt",header=None,sep=" ")

In [47]:
data.head()

0      1     2     3      4     5     6    7     8  9
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.00  1
1  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.00  1
2  1.51743  13.30  3.60  1.14  73.09  0.58  8.17  0.0  0.00  1
3  1.51755  13.00  3.60  1.36  72.99  0.57  8.40  0.0  0.11  1
4  1.51571  12.72  3.46  1.56  73.20  0.67  8.09  0.0  0.24  1

#### 套件 - pandas - 更改colums的名稱

In [48]:
data.columns = ['refractive_index','Sodium','Magnesium','Aluminum',
                'Silicon','Potassium','Calcium','Barium','Iron',
                'Type_of_glass']

In [49]:
data.head()

refractive_index  Sodium  Magnesium  Aluminum  Silicon  Potassium  Calcium  \
0           1.52101   13.64       4.49      1.10    71.78       0.06     8.75   
1           1.51766   13.21       3.69      1.29    72.61       0.57     8.22   
2           1.51743   13.30       3.60      1.14    73.09       0.58     8.17   
3           1.51755   13.00       3.60      1.36    72.99       0.57     8.40   
4           1.51571   12.72       3.46      1.56    73.20       0.67     8.09   

   Barium  Iron  Type_of_glass  
0     0.0  0.00              1  
1     0.0  0.00              1  
2     0.0  0.00              1  
3     0.0  0.11              1  
4     0.0  0.24              1

In [50]:
data['Type_of_glass'] = data['Type_of_glass'].astype('category')

In [51]:
type(data['Type_of_glass'][0])

numpy.int64

In [52]:
data.shape

(114, 10)

#### 套件 - pandas - 獲取dataframe內容

In [53]:
data.ix[0,'Type_of_glass']

C:\Users\js\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


1

In [54]:
data.loc[0]

refractive_index    1.52101
Sodium                13.64
Magnesium              4.49
Aluminum                1.1
Silicon               71.78
Potassium              0.06
Calcium                8.75
Barium                    0
Iron                      0
Type_of_glass             1
Name: 0, dtype: object

In [55]:
data.loc[0][9]

1

#### 分開 X,y

In [65]:
X = data.drop(['Type_of_glass'],axis=1)
y = data.iloc[:,-1]

In [66]:
data['Sodium'].describe()

count    114.000000
mean      13.492368
std        0.808793
min       11.450000
25%       12.982500
50%       13.350000
75%       13.910000
max       17.380000
Name: Sodium, dtype: float64

In [67]:
data1 = pd.concat([X,y], axis=1)

In [68]:
data1.head()

refractive_index  Sodium  Magnesium  Aluminum  Silicon  Potassium  Calcium  \
0           1.52101   13.64       4.49      1.10    71.78       0.06     8.75   
1           1.51766   13.21       3.69      1.29    72.61       0.57     8.22   
2           1.51743   13.30       3.60      1.14    73.09       0.58     8.17   
3           1.51755   13.00       3.60      1.36    72.99       0.57     8.40   
4           1.51571   12.72       3.46      1.56    73.20       0.67     8.09   

   Barium  Iron Type_of_glass  
0     0.0  0.00             1  
1     0.0  0.00             1  
2     0.0  0.00             1  
3     0.0  0.11             1  
4     0.0  0.24             1

#### 由某一行排序資料

In [69]:
X_train.sort_values(['refractive_index'],ascending=True).head()

refractive_index  Sodium  Magnesium  Aluminum  Silicon  Potassium  \
92            1.51115   17.38       0.00      0.34    75.41       0.00   
89            1.51299   14.40       1.74      1.54    74.55       0.00   
83            1.51321   13.00       0.00      3.02    70.70       6.21   
102           1.51531   14.38       0.00      2.66    73.10       0.04   
99            1.51545   14.14       0.00      2.68    73.39       0.08   

     Calcium  Barium  Iron  
92      6.65    0.00  0.00  
89      7.59    0.00  0.00  
83      6.93    0.00  0.00  
102     9.08    0.64  0.00  
99      9.07    0.61  0.05

#### 檢查遺失值

In [70]:
data.isnull().sum()

refractive_index    0
Sodium              0
Magnesium           0
Aluminum            0
Silicon             0
Potassium           0
Calcium             0
Barium              0
Iron                0
Type_of_glass       0
dtype: int64

#### 資料行列反轉

In [71]:
data.T.head()

0        1        2        3        4        5    \
refractive_index  1.52101  1.51766  1.51743  1.51755  1.51571  1.51748   
Sodium              13.64    13.21     13.3       13    12.72    12.86   
Magnesium            4.49     3.69      3.6      3.6     3.46     3.56   
Aluminum              1.1     1.29     1.14     1.36     1.56     1.27   
Silicon             71.78    72.61    73.09    72.99     73.2    73.21   

                      6        7        8        9     ...         104  \
refractive_index  1.51784  1.51735  1.51736  1.51764   ...     1.51514   
Sodium              12.68    13.02    12.78    12.98   ...       14.85   
Magnesium            3.67     3.54     3.62     3.54   ...           0   
Aluminum             1.16     1.69     1.29     1.21   ...        2.42   
Silicon             73.11    72.73    72.79       73   ...       73.72   

                      105      106      107      108      109      110  \
refractive_index  1.51658  1.51617  1.51732  1.51645  1.51623  1.51685   
Sodium               14.8    14.95    14.95    14.94    14.14    14.92   
Magnesium               0        0        0        0        0        0   
Aluminum             1.99     2.27      1.8     1.87     2.88     1.99   
Silicon             73.11     73.3    72.99    73.11    72.61    73.06   

                      111      112      113  
refractive_index  1.52065  1.51651  1.51711  
Sodium              14.36    14.38    14.23  
Magnesium               0        0        0  
Aluminum             2.02     1.94     2.08  
Silicon             73.42    73.61    73.36  

[5 rows x 114 columns]

#### 套件 - sklearn - training set 與 testing set 分開

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,test_size=0.2,random_state=60)

In [74]:
X_train.head()

refractive_index  Sodium  Magnesium  Aluminum  Silicon  Potassium  \
14           1.52210   13.73       3.84      0.72    71.76       0.17   
91           1.51969   14.56       0.00      0.56    73.48       0.00   
78           1.52171   11.56       1.88      1.56    72.86       0.47   
52           1.52081   13.78       2.28      1.43    71.99       0.49   
37           1.51689   12.67       2.88      1.71    73.21       0.73   

    Calcium  Barium  Iron  
14     9.74     0.0  0.00  
91    11.22     0.0  0.00  
78    11.41     0.0  0.00  
52     9.85     0.0  0.17  
37     8.54     0.0  0.00

#### 套件 - sklearn - 建模 Logisstic Reggression

In [75]:
from sklearn.linear_model  import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score

In [76]:
lr=LogisticRegression()

In [77]:
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [78]:
model = lr.fit(X_train,y_train)

In [86]:
model.coef_

array([[-0.00953361, -0.62865072,  1.28587044, -0.95800438,  0.0056183 ,
         0.17178714,  0.42632923, -0.09613956, -0.28479578],
       [-0.01022623, -0.56845919,  0.2175296 ,  0.02880868,  0.08874212,
        -0.02353406,  0.01757427, -1.06010945,  0.29837999],
       [ 0.007291  ,  0.47402642,  0.93982669, -0.76486512, -0.14407843,
        -0.43428519,  0.03826392, -0.03503593,  0.08899728],
       [ 0.01871752,  0.26023247, -0.69110048,  1.40262623, -0.03162126,
        -0.76508952, -0.4837918 ,  1.64079911, -0.13031359],
       [-0.00488334, -0.91932455, -0.77844018,  0.7637213 ,  0.08324139,
         0.75971292,  0.39548052, -0.70150976,  0.1102046 ],
       [-0.0374883 ,  1.20907245, -0.47048034, -0.58054014, -0.21158315,
        -0.67716093, -0.21016495, -1.17172661, -0.15326555]])

In [87]:
pred = model.predict(X_test)

In [88]:
model.predict(X_test)

array([1, 4, 4, 5, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2,
       4], dtype=int64)

In [89]:
pred

array([1, 4, 4, 5, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2,
       4], dtype=int64)

In [90]:
accuracy_score(y_test,pred)

0.6956521739130435

In [91]:
confusion_matrix(y_test,pred)

array([[1, 4, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0],
       [0, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 0, 0]], dtype=int64)

#### 套件 - sklearn - Pipeline

<img src="images.png" width = "600" height = "200" />

<img src="下載.jpg" width = "400"  />

#### 套件 - sklearn - 建模 Random Forest

In [92]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score,cross_val_predict,GridSearchCV
from sklearn.cross_validation import KFold,StratifiedKFold
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.ensemble import RandomForestClassifier

C:\Users\js\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


#### 讀取資料

In [93]:
data = pd.read_table("glass.txt",header=None,sep=" ")

In [94]:
data.columns = ['refractive_index','Sodium','Magnesium','Aluminum',
                'Silicon','Potassium','Calcium','Barium','Iron',
                'Type_of_glass']

#### 建立模型 - 標準化、pca降維、隨機森林

In [127]:
std_scalar = StandardScaler()

In [128]:
pca = PCA()

In [129]:
rf = RandomForestClassifier(n_estimators=100)

In [130]:
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

#### 尋找最佳參數 - cross validation

In [131]:
cvfold = StratifiedKFold(y,n_folds=5,shuffle=False, random_state=0)

In [152]:
steps = [('std_scalar',std_scalar),('PCA',pca),('RF',rf)]

In [133]:
max_depth = range(2,5)
max_leaf_nodes = range(2,5)

In [134]:
model = Pipeline(steps)

In [135]:
param_grid = ({'RF__max_depth':max_depth,'RF__max_leaf_nodes':max_leaf_nodes})

In [136]:
GridSearch_model = GridSearchCV(model,scoring='accuracy',cv=cvfold,param_grid=param_grid)

In [138]:
fit_model = GridSearch_model.fit(X,y)

In [145]:
fit_model.best_params_

{'RF__max_depth': 2, 'RF__max_leaf_nodes': 4}

#### 調整參數後再建立新模型 

In [149]:
rf = RandomForestClassifier(n_estimators=100,max_depth=2,max_leaf_nodes=4,random_state=56)
steps = [('std_scalar',std_scalar),('PCA',pca),('RF',rf)]
model = Pipeline(steps)
model.fit(X,y)
pred = model.predict(X)
accuracy_score(pred,y) # Apparent error rate with grid-search

0.6842105263157895